function getEPG(dirname,FileName)
% Splits Abaqus RPT file into separate field outputs / regions (saved as txt) and gets Nodelabel,
% Nodal Coordinates (Coord1, Coord2, Coord3) and averaged EPG values (saved as mat)

% FileName is the name of the RPT file generated by Abaqus/CAE.
%   To generate an RPT field variable file, do the following in ABAQUS/CAE:
%   1. In the Visualizaiton Module, go to "Report -> Field Output...".
%   2. In the "Variable" tab, choose "Unique Nodal" as the position type.
%   3. Make sure that these are the only boxes checked - COORD1,
%   COORD2,COORD3, EPG Magnitude
%   4. In the "Setup" tab under "Output Format", make sure the layout style
%   is set to "Single table for all field output variables".
%   5. Under "Data", uncheck "Column totals" and "Column
%   min/max" as these are not required. 
cd(dirname)
Str   = fileread(FileName);
CStr  = regexp(Str, '\n', 'split');
Index = [find(strncmp(CStr, 'Field Output reported', 21)), length(CStr) + 1];
for i = 1:(length(Index) - 1)
  Foid = fopen(sprintf('Field_Output_%d.txt', i), 'w');
  if Foid == - 1, error('Less than one instance of field output'); end
  fprintf(Foid, '%s\n', CStr{Index(i):Index(i + 1) - 1});
  fclose(Foid);
end

for i = 1:(length(Index) - 1)
    fid = fopen(sprintf('Field_Output_%d.txt', i), 'r');

    while ~feof(fid)
        fgetl(fid);
        cellData = textscan(fid, '%f %f %f %f %f %f %f');
    end

    EPGData = cell2mat(cellData);
    save(sprintf('Field_Output_%d.mat', i),'EPGData')
    fclose(fid);
end
end
